apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  labels:
    {{- include "test-chart.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        {{- include "test-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name}}
          image: {{ .Values.image.repository}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
